# binance ticker api url
binance_ticker_api : 'https://api.binance.com/api/v3/ticker/price?symbol=BTCUSDT'

# telegram bot token
telegramBotToken : 'your_bot_token'

# telegram Channel id
telegramChannelId : '-1001787262956'
