# binance ticker api url
binance_ticker_api : 'https://api.binance.com/api/v3/ticker/price'

# telegram bot token
telegramBotToken : '5550723317:AAGLeiEGPUj5HW8GGcKi7rFxDg67GrU0dL8'

# telegram Channel id
telegramChannelId : '-1001787262956'

# crypto list to get price data
cryptoList :
  - BTCUSDT
  - ETHUSDT
  - BNBUSDT
  - ADAUSDT
  - XRPUSDT
  - SOLUSDT
  - DOGEUSDT
  - DOTUSDT
  - SHIBUSDT
  - AVAXUSDT
  - MATICUSDT
  - TRXUSDT
  - UNIUSDT
  - WBTCUSDT

# delay time for get data from binance in second
delayTime: 10